"""add password auth fields

Revision ID: 33af957697a1
Revises: da576ab2e532
Create Date: 2025-12-30 15:40:38.135061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33af957697a1'
down_revision: Union[str, Sequence[str], None] = 'da576ab2e532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.alter_column('users', 'google_sub',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'google_sub',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
